controlled_vocab <- list(
  
  study_design = c(
    "case-control",
    "cross-sectional observational, not case-control",
    "time series / longitudinal observational",
    "laboratory experiment",
    "randomized controlled trial",
    "prospective cohort",
    "meta-analysis"
  ),
  
  body_site = "determined by the Uber Anatomy Ontology (Uberon, https://www.ebi.ac.uk/ols4/ontologies/uberon)",
  
  condition = "determined by the Experimental Factor Ontology (EFO, https://www.ebi.ac.uk/efo/)",
  
  sequencing_type = c(
    "16S",
    "18S",
    "WMS",
    "ITS / ITS2",
    "PCR"
  ),
  
  sequencing_platform = c(
    "DNA-DNA Hybridization",
    "Human Intestinal Tract Chip",
    "Illumina",
    "Ion Torrent",
    "Mass spectrometry",
    "Non-quantitative PCR",
    "PacBio Vega (VS)/Revio (RS)/Sequel II",
    "PhyloChip",
    "Roche454",
    "RT-qPCR",
    "Sanger",
    "Nanopore",
    "BGISEQ-500 Sequencing",
    "DNBSEQ-T7",
    "MGISEQ-2000",
    "HTF-Microbi.Array",
    "2b-RAD"
  ),
  
  variable_region_16S = as.character(1:9),
  
  data_transformation = c(
    "raw counts",
    "relative abundances",
    "centered log-ratio",
    "arcsine square-root",
    "log transformation"
  ),
  
  statistical_test = c(
    "ANCOM",
    "ANCOM-BC",
    "ANCOM-BC2",
    "ANOSIM",
    "ANOVA",
    "Beta Binomial Regression",
    "Chi-Square",
    "Cox Proportional-Hazards Regression",
    "Decision Trees (xgBoost, gradient boosting)",
    "Dunn's test",
    "DESeq2",
    "edgeR",
    "Fisher's Exact Test",
    "Fold-change cutoff",
    "Jonckheere's trend test",
    "Kolmogorov-Smirnov Test",
    "Kruskall-Wallis",
    "LASSO Regression",
    "LEfSe",
    "Linear Discriminant Analysis",
    "Linear Regression",
    "Logistic Regression",
    "Mann-Whitney (Wilcoxon)",
    "MaAsLin2",
    "metagenomeSeq",
    "Metastats",
    "Mixed-Effects Regression",
    "Negative Binomial Regression",
    "NLMIXED",
    "Pearson Correlation",
    "PERMANOVA",
    "PLS-DA (Partial least square discriminant analysis)",
    "Post-Hoc Pairwise",
    "Random Forest Analysis",
    "Songbird",
    "Sparse Correlations for Compositional data (SparCC)",
    "Spearman Correlation",
    "Structural Equation Modeling (SEM)",
    "T-Test",
    "treeDA",
    "Wald Test",
    "Welch's T-Test",
    "Zero-Inflated Beta Regression",
    "Zero-Inflated Negative Binomial Regression"
  ),
  
  location = c(
    "Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda",
    "Argentina","Armenia","Australia","Austria","Azerbaijan","Bahamas","Bahrain",
    "Bhutan","Bolivia","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin",
    "Bosnia and Herzegovina","Botswana","Brazil","Brunei Darussalam","Bulgaria",
    "Burkina Faso","Burundi","Cabo Verde","Cambodia","Cameroon","Canada",
    "Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo",
    "Cook Islands","Costa Rica","Croatia","Cuba","Cyprus","Czechia","Côte d'Ivoire",
    "Democratic Republic of the Congo","Denmark","Djibouti","Dominica",
    "Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea",
    "Eritrea","Estonia","Eswatini","Ethiopia","Faroe Islands","Fiji","Finland",
    "France","Gabon","Gambia","Georgia","Germany","Ghana","Greece","Grenada",
    "Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Honduras","Hungary",
    "Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Jamaica",
    "Japan","Jordan","Kazakhstan","Kenya","Kiribati","Kuwait","Kyrgyzstan","Laos",
    "Latvia","Lebanon","Lesotho","Liberia","Libya","Lithuania","Luxembourg",
    "Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands",
    "Mauritania","Mauritius","Mexico","Micronesia","Monaco","Mongolia","Montenegro",
    "Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands",
    "New Zealand","Nicaragua","Niger","Nigeria","Niue","North Korea",
    "North Macedonia","Norway","Oman","Pakistan","Palau","Panama",
    "Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar",
    "Republic of Korea","Republic of Moldova","Romania","Russian Federation",
    "Rwanda","Saint Kitts and Nevis","Saint Lucia",
    "Saint Vincent and the Grenadines","Samoa","San Marino",
    "Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles",
    "Sierra Leone","Singapore","Slovakia","Slovenia","Solomon Islands","Somalia",
    "South Africa","South Korea","South Sudan","Spain","Sri Lanka","Sudan",
    "Suriname","Sweden","Switzerland","Syrian Arab Republic","Taiwan","Tajikistan",
    "Thailand","Timor-Leste","Togo","Tokelau","Tonga","Trinidad and Tobago",
    "Tunisia","Turkey","Turkmenistan","Tuvalu","Uganda","Ukraine",
    "United Arab Emirates","United Kingdom","United Republic of Tanzania",
    "United States of America","Uruguay","Uzbekistan","Vanuatu","Venezuela",
    "Viet Nam","Yemen","Zambia","Zimbabwe","United States-Mexico Border"
  )
)
